# Generated by Django 3.1.1 on 2020-09-29 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcomuna', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(max_length=4)),
            ],
            options={
                'db_table': 'descuento',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=50)),
                ('apellidoPersona', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=13, null=True)),
                ('celular', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('talla', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registrado',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.comuna')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=3)),
                ('codDesc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.descuento')),
                ('codProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.producto')),
            ],
            options={
                'db_table': 'detallePro',
            },
        ),
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('codDetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.detalleproducto')),
                ('codPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.persona')),
            ],
            options={
                'db_table': 'boleta',
            },
        ),
    ]
