# Generated by Django 3.1.1 on 2020-10-22 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='material',
        ),
        migrations.RemoveField(
            model_name='detalleproducto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='idioma',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='nivel',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombrePersona',
            field=models.CharField(max_length=50, verbose_name='Nombre Persona'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='idcom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.comuna', verbose_name='IdComuna'),
        ),
    ]
