# Generated by Django 3.1.2 on 2020-11-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0004_curso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(max_length=70),
        ),
    ]
